version: "3.8"

services:
  frontend:
    build:
      context: ./frontend  # Ensure this points to the frontend directory where package.json is located
    container_name: react-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: flask-backend
    ports:
      - "5000:5000"
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"